project:
  type: book
  pre-render:
    - scripts/check_packages.R

book:
  title: "Statistical Analysis in Sociology"
  author: "Aaron Gullickson"
  chapters:
    - index.qmd
    - part: "The Fundamentals"
      chapters:
        - chapters/chapter_understand_data.qmd
        - chapters/chapter_distribution_variable.qmd
        - chapters/chapter_measure_association.qmd
#   - part: "Going Further"
#     chapters:
  appendices:
    - bibliography/references.qmd


bibliography: bibliography/references.bib

format:
  html:
    theme: flatly
    css: styles.css



