project:
  type: book
  pre-render:
    - scripts/check_packages.R
  execute-dir: project

book:
  title: "Statistical Analysis in Sociology"
  author: "Aaron Gullickson"
  chapters:
    - index.qmd
    - part: "The Fundamentals"
      chapters:
        - chapters/chapter_understand_data.qmd
        - chapters/chapter_look_distributions.qmd
        - chapters/chapter_measure_association.qmd
        - chapters/chapter_make_inferences.qmd
        - chapters/chapter_build_models.qmd
#   - part: "Going Further"
#     chapters:
  appendices:
    - bibliography/references.qmd


bibliography: bibliography/references.bib

format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto
  warning: false
  message: false
number-depth: 1



