project:
  type: book

book:
  title: "Statistical Analysis in Sociology"
  author: "Aaron Gullickson"
  date: "4/5/2022"
  chapters:
    - index.qmd
    - part: "The Fundamentals"
      chapters:
        - chapters/chapter_understand_data.qmd
    - part: "Going Further"
      chapters:
        - chapters/chapter_understand_data.qmd
  appendices:
    - bibliography/references.qmd


bibliography: bibliography/references.bib

format:
  html:
    theme: superhero
  pdf:
    documentclass: scrreprt



